### ISSUE TITLE
Config file not published

### ISSUE THREAD

**Issue by sotengboy** [buglinjo/laravel-webp#1]
Hello, i just install this package through composer, after vendor:publish i didn't see config file laravel-webp.php on config/laravel-webp.php, its normal and i can create it manualy? or i have to reinstall it? i'm using laravel 5.7.

Thanks

**Comment by buglinjo** [comment]
@sotengboy 

I have just tried and the config file was published successfully on Laravel 5.7. What you can try is to just copy the file from `vendor/buglinjo/laravel-webp/config/laravel-webp.php` to your config location: `config/laravel-webp.php`

Lmk if you'll have any more questions. If not I'm going to close this issue in 2 days.

**Comment by sotengboy** [comment]
i just past that step (i think my hosting provider blocked some feature for laravel), i follow next step on the read-me but i got error when upload image, i just put WebP::make($file)->save($this->imagepath); in my media upload controller, and image not upload successfully. what i miss?

**Comment by buglinjo** [comment]
Do you have Webp installed on your hosting server? You can find more details here how to install it on server https://developers.google.com/speed/webp/

**Comment by sotengboy** [comment]
yes i have, and i test via CLI it's work like charm
/libwebp/bin/cwebp -q 70 bep.png -o bep.webp
Saving file 'bep.webp'
File:      bep.png
Dimension: 2000 x 1625 (with alpha)
Output:    46682 bytes Y-U-V-All-PSNR 55.47 48.71 48.49   51.87 dB
block count:  intra4: 286
              intra16: 12464  (-> 97.76%)
              skipped block: 12316 (96.60%)
bytes used:  header:            260  (0.6%)
             mode-partition:   6649  (14.2%)
             transparency:    31833 (99.0 dB)
 Residuals bytes  |segment 1|segment 2|segment 3|segment 4|  total
    macroblocks:  |       0%|       1%|       2%|      96%|   12750
      quantizer:  |      39 |      39 |      38 |      28 |
   filter level:  |      11 |       9 |       8 |       4 |
Lossless-alpha compressed size: 31830 bytes
  * Lossless features used: PALETTE
  * Precision Bits: histogram=6 transform=5 cache=0
  * Palette size:   256

**Comment by sotengboy** [comment]
Hello, i just figured out why it's not working, my hosting provider disabled shell_exec command, so i can not use this package anymore. Thanks for your support.

**Comment by buglinjo** [comment]
I'm adding PHP native Webp support in v2.0 so stay tuned. Thanks for using this package.

**Comment by sotengboy** [comment]
glad to read that, i'll waiting for it.
