### ISSUE TITLE
Drivers[] is not supported

### ISSUE THREAD

**Issue by aliasgarvanak** [buglinjo/laravel-webp#10]
Hello,

I am trying to save the file in my folder but when I upload it it gives me an error Drivers[] not supported. I am running this script in Laravel Lumen API. I am running the system in Windows 10 locally.

**Comment by buglinjo** [comment]
Which driver did you set in your config? Only `cwebp` is available for now.

**Comment by aliasgarvanak** [comment]
'drivers' => [

        'cwebp' => [
            'path' => '/usr/local/bin/cwebp',
        ],

    ],

**Comment by aliasgarvanak** [comment]
I am referring this url

https://github.com/buglinjo/laravel-webp

**Comment by buglinjo** [comment]
![image](https://user-images.githubusercontent.com/1254208/80388161-8c9ff380-8877-11ea-82a4-38bcaa8afc2f.png)
This is where the exception is thrown. It can't find your `$driver`. Make sure you have correctly set up the config file.

**Comment by aliasgarvanak** [comment]
This is my config file. And I am using Lumen


<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Default Quality
    |--------------------------------------------------------------------------
    |
    | This is a default quality unless you provide while generation of the WebP
    |
    */

    'default_quality' => 70,

    /*
    |--------------------------------------------------------------------------
    | Default Driver
    |--------------------------------------------------------------------------
    |
    | This is a default image processing driver. Available: ['cwebp']
    |
    */

    'default_driver' => 'cwebp',

    /*
    |--------------------------------------------------------------------------
    | Drivers
    |--------------------------------------------------------------------------
    |
    | Available drivers which can be selected
    |
    */

    'drivers' => [

        'cwebp' => [
            'path' => '/usr/local/bin/cwebp',
        ],

    ],
];

**Comment by buglinjo** [comment]
Don't forget about `default_driver` inside the config file.

![image](https://user-images.githubusercontent.com/1254208/80388387-d557ac80-8877-11ea-91f4-8b0cda03ae30.png)

**Comment by aliasgarvanak** [comment]
It is the same only

**Comment by aliasgarvanak** [comment]
Also how can i upload it in s3 bucket of AWS ?
