### ISSUE TITLE
Image conversion to WebP using cwebp failed with error code 126

### ISSUE THREAD

**Issue by lizeshakya** [buglinjo/laravel-webp#11]
Hello, 

When I try to save the webp file using command explicitly, it is working fine.

`/home/Desktop/photography/libwebp-1.1.0-rc2-linux-x86-64/bin/cwebp -q 80 lijesh_shakya.jpg -o lijesh_shakya1.webp`

![Screenshot from 2020-05-02 12-42-11](https://user-images.githubusercontent.com/20186159/80857497-682a8980-8c72-11ea-95bd-3c5dfad40ad5.png)

Problem arose when I gave the same path for cwebp in `config/laravel-webp.php` file like:

```
'drivers' => [

        'cwebp' => [
            'path' => '/home/Desktop/photography/libwebp-1.1.0-rc2-linux-x86-64/bin/cwebp',
        ],

    ],
```
And for saving code like: 

```
Route::post('test.store', function(Request $request){
    $webp = \Webp::make($request->file('name'));
    if ($webp->save(storage_path('app/output.webp'))) {
        dd("worked");
    }else{
        dd('not worked');
    }
})->name('test.store');
```

It throws me an error like:

> Buglinjo\LaravelWebp\CwebpShellExecutionFailed
> Image conversion to WebP using cwebp failed with error code 126. This command was used to execute cwebp: /home/Desktop/photography/libwebp-1.1.0-rc2-linux-x86-64/bin/cwebp -q 80 /tmp/php3LZ0HJ -o /var/www/html/photography/storage/app/output.webp No output was sent to stdout

**Comment by buglinjo** [comment]
I can't reproduce. Please add more details.

**Comment by dani-fadli** [comment]
Have you solved the problem? I got the same error message here. The webp converter works fine in my local Windows, but I get this error when using it on the Linux server. I have downloaded and put the 64-bit-Linux-cwebp library same as the windows library inside the storage/app folder, and have changed the path inside the laravel-webp.php config file with storage_path()

**Comment by lizeshakya** [comment]
Hello, sorry for the late reply. I used [Intervention/Image](http://image.intervention.io/getting_started/introduction) package in order to convert to webp format.

```
public function convertToWebp(\Intervention\Image\Image $image)
    {
        return $image->encode('webp');
    }
```

I was unable to come up with the solution in this package.

**Comment by dani-fadli** [comment]
After some search and ask my DevOps, I have found that this kind of error is caused by the package can't find the cwebp driver from the path I mentioned in the `laravel-webp.php` config in the server. In Linux, the driver should be installed in the computer system as refer to [this](https://developers.google.com/speed/webp/docs/compiling#unix) site.
