### ISSUE TITLE
Image conversion to WebP using cwebp failed with error code 1

### ISSUE THREAD

**Issue by bhawanig** [buglinjo/laravel-webp#12]
Hello,

When I try to save the webp file using command explicitly, it is working fine.

![Capture](https://user-images.githubusercontent.com/59812124/86236794-48eba200-bbb8-11ea-8eb7-d3302137c0b2.PNG)

Problem arise when I gave the same path for cwebp in config/laravel-webp.php file like:

    'drivers' => [

        'cwebp' => [
            'path' => 'C:/Users/dannyl/Downloads/libwebp-1.1.0-windows-x64 (2)/libwebp-1.1.0-windows-x64/bin/cwebp',
        ],

    ],
And for saving code like:
                 $path = "F:/test/property_images/";
                $webp = Webp::make($request->file('profile_pic'));

                if ($webp->save($path.'output.webp')) {
                    // File is saved successfully
                    echo "file saved sccuess";
                }

**Comment by buglinjo** [comment]
it should be a permissions issue in windows. Please check if laravel app can access that location.

**Comment by bhawanig** [comment]
thanks for your reply I have solved it myself, actually the code working fine in my case after putting the cwep file in C drive like "C:\libwebp-1.1.0-windows-x64", 
so can you please explain how we can deploy it on live server let say my hosting is on GoDaddy server

**Comment by abdellahrk** [comment]
Hello @buglinjo , having this issue in Laravel 7. Can you help?
Thanks.
