### ISSUE TITLE
Class 'Laravel\Socialite\SocialiteServiceProvider' not found

### ISSUE THREAD

**Issue by cantacom-dev** [buglinjo/laravel-webp#13]
Hello. I'm having difficulties with this error

**Class 'Laravel\Socialite\SocialiteServiceProvider' not found**

How can I solve?

**Comment by buglinjo** [comment]
How is that connected to laravel-webp package?

**Comment by cantacom-dev** [comment]
I performed the entire installation process of the webp package according to the documentation. When I call the method inside my controller this error is replicated.

**Comment by buglinjo** [comment]
Laravel socialite is a completely different package and is not connected to laravel-webp. Please read the docs here: https://laravel.com/docs/7.x/socialite

**Comment by cantacom-dev** [comment]
Excuse me! I got confused. The error presented is this:

Image conversion to WebP using cwebp failed with error code 1.\nThis command was used to execute cwebp: \n  /usr/local/bin/cwebp -q 70

**Comment by syntafin** [comment]
Is cwebp installed in your PATH?
