### ISSUE TITLE
Image conversion to WebP using cwebp failed with error code 1.

### ISSUE THREAD

**Issue by adrian-stein** [buglinjo/laravel-webp#18]
On windows and I get this error when running it.
```
Image conversion to WebP using cwebp failed with error code 1.
This command was used to execute cwebp:
C:\Program Files (x86)/libwebp-1.2.0-windows-x64/bin/cwebp -q 80 C:\wamp64\tmp\image 5585.jpg -o C:\ .... \boilerplate\storage\app/webp/image 5585.webp
No output was sent to stdout
```

It looks like it doesnt like the space in my file paths. If in Cwebp Class in the save function you change the line to the following add the quotes It allows for spaces. 

`$cmd = '"' . $this->cwebpPath . '" -q ' . $quality . ' "' . $this->image->getPathname() . '" -o "' . $outputPath . '"';`

Any chance you can get this fixed up asap? or is there a work around for it?

I can do this in my config file but doesnt allow for spaces in file name so a fix for al would be good.

```
'drivers' => [
                    'php-gd' => [],
                    'cwebp' => [
                        'path' => '"C:\Program Files (x86)/libwebp-1.2.0-windows-x64/bin/cwebp.exe"',
                    ],
                ],
```

**Comment by buglinjo** [comment]
I see that you have space in the image name which splits up the arguments to the executable.
