### ISSUE TITLE
Image conversion to WebP using cwebp failed with error code 1.

### ISSUE THREAD

**Issue by momin678** [buglinjo/laravel-webp#19]
when I submit the form than show this error
<img width="900" alt="Screenshot 2021-08-12 002103" src="https://user-images.githubusercontent.com/75216819/129082571-32a59910-f810-498c-8cb7-17ac5a5084cd.png">

its controller function 
    public function webp_image_store(Request $request){
            $webp = Webp::make($request->file('images'));
            if ($webp->save(public_path('webp_img))) {
                // File is saved successfully
                return back();
            }
        }
And its laravel-webp.php

    'drivers' => [
        'cwebp' => [
            'path' => '/usr/local/bin/cwebp',
        ],
    ],

please tell me now which part change than I will get success result

**Comment by buglinjo** [comment]
Make sure your path to the `cwebp` executable is correct. I see that you are using windows, so I think `cwebp.exe` should be in a different place than `/usr/local/bin/`
