### ISSUE TITLE
Problem with function make

### ISSUE THREAD

**Issue by Kkiomen** [buglinjo/laravel-webp#22]
`
$webp = Webp::make($request->file);
                    if ($webp->save(public_path($this->directory. '/'. $filenameWithoutExtension. '.webp'))) {
                        echo 'test';
                        die;
                    }
`

and I try with

`$webp = Webp::make($request->file('file'));
                    if ($webp->save(public_path($this->directory. '/'. $filenameWithoutExtension. '.webp'))) {
                        echo 'test';
                        die;
                    }`

and i have the same problem "array_keys(): Argument #1 ($array) must be of type array, null given"
with funcion Webp::make

**Comment by buglinjo** [comment]
`$request->file` is not correct. File is a method under request class which takes arguments :)

**Comment by Kkiomen** [comment]
so i use $request->file('file')
method show me: https://i.imgur.com/Nao5qqv.png
but when i put this to Webp::make().... i have all times the same problem: 
`array_keys(): Argument #1 ($array) must be of type array, null given`
but when I check like
`                    if(is_null($request->file('file'))){
                        dd($request->file('file'));
                    }
                    $webp = Webp::make($request->file('file'));`
                    
$request->file('file') is not null




....
Maybe this is first problem:
https://i.imgur.com/dUd15jU.png

**Comment by mertayasa** [comment]
found the same issue too, php8, gd, laravel 8

**Comment by buglinjo** [comment]
The publisher has been fixed in the newest release of v2.3.1 - https://github.com/buglinjo/laravel-webp/commit/8d28bad5dbb82d7257eb77f27b5c57daa0c0d6b8

Please update dependencies and try to re-publish the config assets.

**Comment by mertayasa** [comment]
thanks bro..  appreciate that
