### ISSUE TITLE
Overrides to config file when runs composer update command

### ISSUE THREAD

**Issue by ysfkaya** [buglinjo/laravel-webp#24]
Hi. I noticed a minor bug in the Service Provider.

You had set a publish path grouped as `laravel-assets` in provider file. I think that part should be removed.

Steps To Reproduce:

- Publish the config file on fresh laravel project.
- Change the path for cwebp driver in the `config/laravel-webp.php` file
- Run `composer update` command
- And you will see changed the config file

**Comment by buglinjo** [comment]
You're right, fixing the issue now
