### ISSUE TITLE
Not working when use fetch/ajax

### ISSUE THREAD

**Issue by binsarjr** [buglinjo/laravel-webp#27]
Why i get response "failed to load response" if use laravel-webp?

When i comment the line,its work

**Comment by binsarjr** [comment]
Ah sorry. Something error on my Middleware

**Comment by buglinjo** [comment]
Can you elaborate more? It is unclear what is the issue.

**Comment by binsarjr** [comment]
sorry I forgot to tell. this has been resolved, the problem was apparently because vite refreshed the page when there was a change in the `storage` and `public/storage` folders.

the fix is enough to ignore the folder that will be watched
