### ISSUE TITLE
Webp::make($file)->save($path) returns true but can't find an image on given path

### ISSUE THREAD

**Issue by JignasaSutariya** [buglinjo/laravel-webp#3]
The issue occurred while  working on Laravel 5.8 with php version 7.2

I'm using `cwebp` as a default driver, `/usr/local/bin/cwebp` as a path for cwebp.
And trying to convert my jpeg image to webp image using following code
`$webp = Webp::make($file)->save($path);`
Here, `$webp` returns true but, I can't find moved image on the path `$path`

**Comment by buglinjo** [comment]
Are you sure you have specified the path correctly? `save($outputPath)` function returns `File::exists($outputPath)` so it will be false if it does not exist.

**Comment by JignasaSutariya** [comment]
Yeah, you are right, the path that I had added was right as per folder structure but, `cwebp` was not installed over there. So, the function was returning true but the result was not as expected.

**Comment by 94praneeth** [comment]
> Yeah, you are right, the path that I had added was right as per folder structure but, `cwebp` was not installed over there. So, the function was returning true but the result was not as expected.

I have the same issue. But how would i find the right path for the **cwebp**?
I've installed the `cwebp` using `sudo apt install webp`. Also edited `config/laravel-webp.php` as follow,

`'drivers' => [

        'cwebp' => [
            'path' => '/usr/bin/cwebp',
        ],

    ],`

Still not working.

**Comment by buglinjo** [comment]
Sorry for the late response. Somehow this question slipped through my notifications. 
To find the correct path to `cwebp` on Linux, use `which cwebp` command, which will return the full path to `cwebp`.
