### ISSUE TITLE
Unnecessary output

### ISSUE THREAD

**Issue by terax6669** [buglinjo/laravel-webp#31]
Running `\Webp::make($file)->save($path);` when using `cwebp` results in printing:

```
Saving file '/var/www/html/storage/app/temp/test1.webp'
File:      /tmp/phpdhNICn
Dimension: 50 x 50
Output:    64 bytes Y-U-V-All-PSNR 99.00 99.00 99.00   99.00 dB
           (0.20 bpp)
block count:  intra4:          0  (0.00%)
              intra16:        16  (100.00%)
              skipped:        15  (93.75%)
bytes used:  header:             16  (25.0%)
             mode-partition:     10  (15.6%)
 Residuals bytes  |segment 1|segment 2|segment 3|segment 4|  total
    macroblocks:  |       6%|       0%|       0%|      94%|      16
      quantizer:  |      12 |      12 |      11 |       8 |
   filter level:  |       4 |       3 |       2 |       0 |
```

Please add `-quiet` or consider using something that will capture the output (like Symfony's Process class).

**Comment by buglinjo** [comment]
Hey, unfortunately I do not have much time to maintain the package. Pull requests are very welcome.

**Comment by terax6669** [comment]
> Pull requests are very welcome.

@buglinjo Is there something wrong with the PR I made?

**Comment by buglinjo** [comment]
Merged

**Comment by buglinjo** [comment]
@terax6669 As your changes were breaking change for older laravel versions I had to introduce V3.0. 

Here's the full release: https://github.com/buglinjo/laravel-webp/releases/tag/v3.0.0
